### ISSUE TITLE
DDL generation

### ISSUE THREAD

**Issue by simonkelly1973** [mdpnp/mdpnp#65]
We have done quite a lot of work on generating DDL for for ice DDS entities, but we don't have a record of it here as it was done in a clone of the repository.

**Comment by simonkelly1973** [comment]
a1cf346 fixes an issue that caused the following stack trace

Exception in thread "main" java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
        at java.util.regex.Pattern.error(Pattern.java:1957)
        at java.util.regex.Pattern.compile(Pattern.java:1704)
        at java.util.regex.Pattern.<init>(Pattern.java:1351)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.lang.String.split(String.java:2380)
        at java.lang.String.split(String.java:2422)
        at org.mdpnp.sql.SQLDatabaseValidator.getTableNameFromResourcePath(SQLDatabaseValidator.java:29)
        at org.mdpnp.sql.SQLDatabaseValidator.validate(SQLDatabaseValidator.java:67)
        at org.mdpnp.apps.testapp.Main.main(Main.java:60)

This happened because Path.separator on Windows returns just a single '\' character.  When that is passed into Pattern, split etc. it fails.  The new "escape" method doubles it up as \\ , and that fixes the problem.
